// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@2.49.8";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in SoMA user's profile (id, name, email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const { data, error } = await sb(ctx).from("profiles").select("id, full_name, email, avatar_url").eq("id", userId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = data ?? { id: userId, email: ctx.getUserEmail() ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(profile) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/list-boards.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.49.8";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_boards_default = defineTool2({
  name: "list_boards",
  title: "List boards",
  description: "List SoMA boards the signed-in user has access to (via RLS).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(50).describe("Max boards to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("boards").select("id, name, description, team_id, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { boards: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-demands.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.49.8";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_demands_default = defineTool3({
  name: "list_my_demands",
  title: "List my demands",
  description: "List demands where the signed-in user is a responsible or follower assignee. Optionally filter by board.",
  inputSchema: {
    board_id: z2.string().uuid().optional().describe("Optional board UUID to filter by."),
    include_archived: z2.boolean().default(false).describe("Include archived demands."),
    limit: z2.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ board_id, include_archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb3(ctx);
    const userId = ctx.getUserId();
    const { data: assignments, error: aErr } = await client.from("demand_assignees").select("demand_id").eq("user_id", userId);
    if (aErr) return { content: [{ type: "text", text: aErr.message }], isError: true };
    const ids = (assignments ?? []).map((a) => a.demand_id);
    if (ids.length === 0) {
      return {
        content: [{ type: "text", text: "[]" }],
        structuredContent: { demands: [] }
      };
    }
    let query = client.from("demands").select("id, title, description, status_id, board_id, priority, due_date, created_at, archived").in("id", ids).order("created_at", { ascending: false }).limit(limit);
    if (board_id) query = query.eq("board_id", board_id);
    if (!include_archived) query = query.eq("archived", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { demands: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-demands.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@2.49.8";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_demands_default = defineTool4({
  name: "search_demands",
  title: "Search demands",
  description: "Search SoMA demands the signed-in user can see (via RLS) by title/description substring.",
  inputSchema: {
    query: z3.string().min(1).describe("Text to match in demand title or description."),
    board_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, board_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const escaped = query.replace(/[%_]/g, (m) => `\\${m}`);
    let q = sb4(ctx).from("demands").select("id, title, description, status_id, board_id, priority, due_date, created_at").or(`title.ilike.%${escaped}%,description.ilike.%${escaped}%`).eq("archived", false).order("created_at", { ascending: false }).limit(limit);
    if (board_id) q = q.eq("board_id", board_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { demands: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-demand.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@2.49.8";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_demand_default = defineTool5({
  name: "get_demand",
  title: "Get demand",
  description: "Fetch a single SoMA demand by id, including its assignees.",
  inputSchema: {
    demand_id: z4.string().uuid().describe("Demand UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ demand_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sb5(ctx);
    const { data: demand, error } = await client.from("demands").select(
      "id, title, description, status_id, board_id, team_id, priority, due_date, created_at, delivered_at, archived"
    ).eq("id", demand_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!demand) return { content: [{ type: "text", text: "Demand not found" }], isError: true };
    const { data: assignees } = await client.from("demand_assignees").select("user_id, is_primary").eq("demand_id", demand_id);
    const result = { ...demand, assignees: assignees ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: { demand: result }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "erxhxmetrvkigjwxchbj";
var mcp_default = defineMcp({
  name: "soma-mcp",
  title: "SoMA \u2014 Gest\xE3o de Demandas",
  version: "0.1.0",
  instructions: "Ferramentas de leitura para a plataforma SoMA (quadros, demandas e perfil do usu\xE1rio). Todas as chamadas respeitam as permiss\xF5es (RLS) do usu\xE1rio autenticado. Use `whoami` para confirmar a sess\xE3o, `list_boards` para descobrir quadros, `list_my_demands` para ver as demandas do usu\xE1rio, `search_demands` para busca por texto, e `get_demand` para detalhes de uma demanda espec\xEDfica.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_boards_default, list_my_demands_default, search_demands_default, get_demand_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
