// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoamiTool = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in SoMA user's id and email from the verified OAuth token.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "PERMISSION_DENIED: Not authenticated" }], isError: true };
    }
    const payload = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "erxhxmetrvkigjwxchbj";
var mcp_default = defineMcp({
  name: "soma-mcp",
  title: "SoMA \u2014 Opera\xE7\xF5es (Marketing OS)",
  version: "2.0.0",
  instructions: [
    "Servidor MCP do SoMA (reset m\xEDnimo).",
    "Somente a ferramenta `whoami` est\xE1 dispon\xEDvel \u2014 use-a para validar a conex\xE3o OAuth.",
    "As demais ferramentas ser\xE3o restauradas ap\xF3s validar a conex\xE3o."
  ].join("\n"),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoamiTool]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
