CREATE TRIGGER update_board_approval_notify_settings_updated_at BEFORE UPDATE ON board_approval_notify_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_enforce_board_limit BEFORE INSERT ON boards FOR EACH ROW EXECUTE FUNCTION enforce_board_limit();
CREATE TRIGGER update_boards_updated_at BEFORE UPDATE ON boards FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER update_contracts_updated_at BEFORE UPDATE ON contracts FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER demand_approval_notify_settings_updated_at BEFORE UPDATE ON demand_approval_notify_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER on_assignee_added AFTER INSERT ON demand_assignees FOR EACH ROW EXECUTE FUNCTION notify_assignee_added();
CREATE TRIGGER on_interaction_mention AFTER INSERT ON demand_interactions FOR EACH ROW WHEN (new.content IS NOT NULL AND new.content LIKE '%@%') EXECUTE FUNCTION notify_mention();
CREATE TRIGGER on_request_comment_created AFTER INSERT ON demand_request_comments FOR EACH ROW EXECUTE FUNCTION notify_request_comment_created();
CREATE TRIGGER update_demand_request_comments_updated_at BEFORE UPDATE ON demand_request_comments FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER on_demand_request_created AFTER INSERT ON demand_requests FOR EACH ROW EXECUTE FUNCTION notify_demand_request_created();
CREATE TRIGGER on_demand_request_status_changed AFTER UPDATE ON demand_requests FOR EACH ROW EXECUTE FUNCTION notify_demand_request_status_changed();
CREATE TRIGGER update_demand_requests_updated_at BEFORE UPDATE ON demand_requests FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER update_demand_subtasks_updated_at BEFORE UPDATE ON demand_subtasks FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER update_demand_templates_updated_at BEFORE UPDATE ON demand_templates FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER enforce_dependency_status BEFORE UPDATE ON demands FOR EACH ROW EXECUTE FUNCTION enforce_demand_dependency();
CREATE TRIGGER notify_adjustment_completed_trigger AFTER UPDATE ON demands FOR EACH ROW EXECUTE FUNCTION notify_adjustment_completed();
CREATE TRIGGER on_demand_assigned AFTER UPDATE ON demands FOR EACH ROW EXECUTE FUNCTION notify_demand_assigned();
CREATE TRIGGER on_demand_create_update_usage AFTER INSERT ON demands FOR EACH ROW EXECUTE FUNCTION update_usage_on_demand_create();
CREATE TRIGGER on_demand_created AFTER INSERT ON demands FOR EACH ROW EXECUTE FUNCTION notify_demand_created();
CREATE TRIGGER on_demand_status_changed AFTER UPDATE ON demands FOR EACH ROW EXECUTE FUNCTION notify_demand_status_changed();
CREATE TRIGGER set_updated_at_demands BEFORE UPDATE ON demands FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER track_time_in_progress BEFORE UPDATE OF status_id ON demands FOR EACH ROW EXECUTE FUNCTION update_time_in_progress();
CREATE TRIGGER trg_compute_demand_is_overdue BEFORE INSERT OR UPDATE OF due_date, status_id, delivered_at ON demands FOR EACH ROW EXECUTE FUNCTION compute_demand_is_overdue();
CREATE TRIGGER trg_enforce_demand_monthly_limit BEFORE INSERT ON demands FOR EACH ROW EXECUTE FUNCTION enforce_demand_monthly_limit();
CREATE TRIGGER trg_normalize_demand_due_date BEFORE INSERT OR UPDATE OF due_date ON demands FOR EACH ROW EXECUTE FUNCTION normalize_demand_due_date();
CREATE TRIGGER trg_set_subdemand_sort_order BEFORE INSERT ON demands FOR EACH ROW EXECUTE FUNCTION set_subdemand_sort_order();
CREATE TRIGGER trigger_reassign_demand_sequence BEFORE UPDATE OF board_id ON demands FOR EACH ROW EXECUTE FUNCTION reassign_demand_sequence_on_board_change();
CREATE TRIGGER trigger_set_demand_delivered_at BEFORE UPDATE ON demands FOR EACH ROW EXECUTE FUNCTION set_demand_delivered_at();
CREATE TRIGGER trigger_set_demand_sequence BEFORE INSERT ON demands FOR EACH ROW WHEN (new.board_sequence_number IS NULL) EXECUTE FUNCTION set_demand_sequence_number();
CREATE TRIGGER trigger_update_status_changed_at BEFORE UPDATE ON demands FOR EACH ROW EXECUTE FUNCTION update_status_changed_at();
CREATE TRIGGER trg_enforce_note_limit BEFORE INSERT ON notes FOR EACH ROW EXECUTE FUNCTION enforce_note_limit();
CREATE TRIGGER update_notes_updated_at BEFORE UPDATE ON notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_payments_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_profiles BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER update_demand_folders_updated_at BEFORE UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER update_recurring_demands_updated_at BEFORE UPDATE ON recurring_demands FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER validate_recurring_demand_frequency_trigger BEFORE INSERT OR UPDATE ON recurring_demands FOR EACH ROW EXECUTE FUNCTION validate_recurring_demand_frequency();
CREATE TRIGGER trg_enforce_service_limit BEFORE INSERT ON services FOR EACH ROW EXECUTE FUNCTION enforce_service_limit();
CREATE TRIGGER update_services_updated_at BEFORE UPDATE ON services FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER update_subscriptions_updated_at BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER on_team_join_request_created AFTER INSERT ON team_join_requests FOR EACH ROW EXECUTE FUNCTION notify_team_join_request_created();
CREATE TRIGGER on_team_join_request_responded AFTER UPDATE ON team_join_requests FOR EACH ROW EXECUTE FUNCTION notify_team_join_request_responded();
CREATE TRIGGER on_team_member_added AFTER INSERT ON team_members FOR EACH ROW EXECUTE FUNCTION add_member_to_default_board();
CREATE TRIGGER trg_enforce_team_member_limit BEFORE INSERT ON team_members FOR EACH ROW EXECUTE FUNCTION enforce_team_member_limit();
CREATE TRIGGER set_updated_at_teams BEFORE UPDATE ON teams FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER trg_create_trial_subscription AFTER INSERT ON teams FOR EACH ROW EXECUTE FUNCTION create_trial_subscription_for_team();
CREATE TRIGGER update_user_preferences_updated_at BEFORE UPDATE ON user_preferences FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER update_webhook_subscriptions_updated_at BEFORE UPDATE ON webhook_subscriptions FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_approval_notify_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_summary_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_summary_share_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_whatsapp_keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_approval_notify_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_assignees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_request_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_request_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_share_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_subtasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demand_time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.google_calendar_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.note_share_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.note_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.note_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_demands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recurring_demands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_join_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trial_coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_inbound_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_phone_codes ENABLE ROW LEVEL SECURITY;