CREATE POLICY "Team admins can manage API keys" ON public.api_keys FOR ALL TO public USING (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team admins can view API logs" ON public.api_logs FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM api_keys ak WHERE ((ak.id = api_logs.api_key_id) AND is_team_admin(auth.uid(), ak.team_id)))));
CREATE POLICY "Board admins/moderators can delete approval notify settings" ON public.board_approval_notify_settings FOR DELETE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins/moderators can insert approval notify settings" ON public.board_approval_notify_settings FOR INSERT TO public WITH CHECK (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins/moderators can update approval notify settings" ON public.board_approval_notify_settings FOR UPDATE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id)) WITH CHECK (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board members can view approval notify settings" ON public.board_approval_notify_settings FOR SELECT TO public USING (is_board_member(auth.uid(), board_id));
CREATE POLICY "Board admins/moderators can add members" ON public.board_members FOR INSERT TO public WITH CHECK (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins/moderators can remove members" ON public.board_members FOR DELETE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins/moderators can update member roles" ON public.board_members FOR UPDATE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board members can view other members" ON public.board_members FOR SELECT TO public USING ((board_id IN ( SELECT get_user_board_ids(auth.uid()))));
CREATE POLICY "Team admins/moderators can add board members" ON public.board_members FOR INSERT TO public WITH CHECK (is_team_admin_or_moderator_for_board(auth.uid(), board_id));
CREATE POLICY "Team admins/moderators can remove board members" ON public.board_members FOR DELETE TO public USING (is_team_admin_or_moderator_for_board(auth.uid(), board_id));
CREATE POLICY "Team admins/moderators can update board members" ON public.board_members FOR UPDATE TO public USING (is_team_admin_or_moderator_for_board(auth.uid(), board_id)) WITH CHECK (is_team_admin_or_moderator_for_board(auth.uid(), board_id));
CREATE POLICY "Team admins/moderators can view board members" ON public.board_members FOR SELECT TO public USING (is_team_admin_or_moderator_for_board(auth.uid(), board_id));
CREATE POLICY "Board admins can delete board_services" ON public.board_services FOR DELETE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins can insert board_services" ON public.board_services FOR INSERT TO public WITH CHECK (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins can update board_services" ON public.board_services FOR UPDATE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board members can view board_services" ON public.board_services FOR SELECT TO public USING (is_board_member(auth.uid(), board_id));
CREATE POLICY "Team admins/moderators can view board services" ON public.board_services FOR SELECT TO public USING (is_team_admin_or_moderator_for_board(auth.uid(), board_id));
CREATE POLICY "Board admins can delete board_statuses" ON public.board_statuses FOR DELETE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins can insert board_statuses" ON public.board_statuses FOR INSERT TO public WITH CHECK (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins can update board_statuses" ON public.board_statuses FOR UPDATE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board members can view board_statuses" ON public.board_statuses FOR SELECT TO public USING (is_board_member(auth.uid(), board_id));
CREATE POLICY "Team admins/moderators can delete board_statuses" ON public.board_statuses FOR DELETE TO authenticated USING (is_team_admin_or_moderator_for_board(auth.uid(), board_id));
CREATE POLICY "Team admins/moderators can update board_statuses" ON public.board_statuses FOR UPDATE TO authenticated USING (is_team_admin_or_moderator_for_board(auth.uid(), board_id));
CREATE POLICY "Team admins/moderators can view board_statuses" ON public.board_statuses FOR SELECT TO authenticated USING (is_team_admin_or_moderator_for_board(auth.uid(), board_id));
CREATE POLICY "Board members can create summaries" ON public.board_summary_history FOR INSERT TO public WITH CHECK (((auth.uid() = created_by) AND (EXISTS ( SELECT 1 FROM board_members bm WHERE ((bm.board_id = board_summary_history.board_id) AND (bm.user_id = auth.uid()))))));
CREATE POLICY "Board members can view summaries" ON public.board_summary_history FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM board_members bm WHERE ((bm.board_id = board_summary_history.board_id) AND (bm.user_id = auth.uid())))));
CREATE POLICY "Summary creator can delete" ON public.board_summary_history FOR DELETE TO public USING ((auth.uid() = created_by));
CREATE POLICY "Board members can view tokens" ON public.board_summary_share_tokens FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM (board_summary_history bsh JOIN board_members bm ON ((bm.board_id = bsh.board_id))) WHERE ((bsh.id = board_summary_share_tokens.summary_id) AND (bm.user_id = auth.uid())))));
CREATE POLICY "Token creators can manage tokens" ON public.board_summary_share_tokens FOR ALL TO public USING ((auth.uid() = created_by));
CREATE POLICY "Board admins/moderators manage keywords" ON public.board_whatsapp_keywords FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM board_members bm WHERE ((bm.board_id = board_whatsapp_keywords.board_id) AND (bm.user_id = auth.uid()) AND (bm.role = ANY (ARRAY['admin'::team_role, 'moderator'::team_role])))))) WITH CHECK ((EXISTS ( SELECT 1 FROM board_members bm WHERE ((bm.board_id = board_whatsapp_keywords.board_id) AND (bm.user_id = auth.uid()) AND (bm.role = ANY (ARRAY['admin'::team_role, 'moderator'::team_role]))))));
CREATE POLICY "Members can view board keywords" ON public.board_whatsapp_keywords FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM board_members bm WHERE ((bm.board_id = board_whatsapp_keywords.board_id) AND (bm.user_id = auth.uid())))));
CREATE POLICY "Board admins can delete boards" ON public.boards FOR DELETE TO authenticated USING (is_board_admin_or_moderator(auth.uid(), id));
CREATE POLICY "Board admins can update boards" ON public.boards FOR UPDATE TO authenticated USING (is_board_admin_or_moderator(auth.uid(), id)) WITH CHECK (is_board_admin_or_moderator(auth.uid(), id));
CREATE POLICY "Board admins/moderators can update boards" ON public.boards FOR UPDATE TO authenticated USING (is_board_admin_or_moderator(auth.uid(), id));
CREATE POLICY "Board members can view their boards" ON public.boards FOR SELECT TO public USING ((id IN ( SELECT get_user_board_ids(auth.uid()))));
CREATE POLICY "Team members can view boards" ON public.boards FOR SELECT TO authenticated USING (((id IN ( SELECT board_members.board_id FROM board_members WHERE (board_members.user_id = auth.uid()))) OR is_team_admin_or_moderator(auth.uid(), team_id)));
CREATE POLICY "Team owners can create boards" ON public.boards FOR INSERT TO authenticated WITH CHECK (is_team_owner(auth.uid(), team_id));
CREATE POLICY "Team owners can delete non-default boards" ON public.boards FOR DELETE TO authenticated USING (is_team_owner(auth.uid(), team_id));
CREATE POLICY "Admins and moderators can delete contracts" ON public.contracts FOR DELETE TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Admins and moderators can insert contracts" ON public.contracts FOR INSERT TO public WITH CHECK (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Admins and moderators can update contracts" ON public.contracts FOR UPDATE TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team members can view contracts" ON public.contracts FOR SELECT TO public USING (is_team_member(auth.uid(), team_id));
CREATE POLICY "Admins can view all redemptions" ON public.coupon_redemptions FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Team members can view redemptions" ON public.coupon_redemptions FOR SELECT TO authenticated USING (is_team_member(auth.uid(), team_id));
CREATE POLICY "Board members can delete demand approval settings" ON public.demand_approval_notify_settings FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1 FROM demands d WHERE ((d.id = demand_approval_notify_settings.demand_id) AND is_board_member(auth.uid(), d.board_id)))));
CREATE POLICY "Board members can insert demand approval settings" ON public.demand_approval_notify_settings FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1 FROM demands d WHERE ((d.id = demand_approval_notify_settings.demand_id) AND is_board_member(auth.uid(), d.board_id)))));
CREATE POLICY "Board members can update demand approval settings" ON public.demand_approval_notify_settings FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1 FROM demands d WHERE ((d.id = demand_approval_notify_settings.demand_id) AND is_board_member(auth.uid(), d.board_id)))));
CREATE POLICY "Board members can view demand approval settings" ON public.demand_approval_notify_settings FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM demands d WHERE ((d.id = demand_approval_notify_settings.demand_id) AND is_board_member(auth.uid(), d.board_id)))));
CREATE POLICY "Anonymous can view assignees for shared demands" ON public.demand_assignees FOR SELECT TO authenticated, anon USING (is_demand_shared(demand_id));
CREATE POLICY "Team members can view assignees" ON public.demand_assignees FOR SELECT TO public USING ((demand_id IN ( SELECT demands.id FROM demands WHERE (demands.team_id IN ( SELECT get_user_team_ids(auth.uid()))))));
CREATE POLICY "Users allowed can add demand assignees" ON public.demand_assignees FOR INSERT TO authenticated WITH CHECK (can_manage_demand_assignees(auth.uid(), demand_id));
CREATE POLICY "Users allowed can remove demand assignees" ON public.demand_assignees FOR DELETE TO authenticated USING (can_manage_demand_assignees(auth.uid(), demand_id));
CREATE POLICY "Users allowed can update demand assignees" ON public.demand_assignees FOR UPDATE TO authenticated USING (can_manage_demand_assignees(auth.uid(), demand_id)) WITH CHECK (can_manage_demand_assignees(auth.uid(), demand_id));
CREATE POLICY "Anonymous can view attachments for shared demands" ON public.demand_attachments FOR SELECT TO authenticated, anon USING (is_demand_shared(demand_id));
CREATE POLICY "Team members can upload attachments" ON public.demand_attachments FOR INSERT TO public WITH CHECK (((demand_id IN ( SELECT d.id FROM demands d WHERE (d.team_id IN ( SELECT get_user_team_ids(auth.uid()))))) AND (uploaded_by = auth.uid())));
CREATE POLICY "Team members can view attachments" ON public.demand_attachments FOR SELECT TO public USING ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.team_id IN ( SELECT get_user_team_ids(auth.uid()))))));
CREATE POLICY "Users can delete own attachments" ON public.demand_attachments FOR DELETE TO public USING ((uploaded_by = auth.uid()));
CREATE POLICY "Board members can manage dependencies" ON public.demand_dependencies FOR ALL TO authenticated USING ((EXISTS ( SELECT 1 FROM (demands d JOIN board_members bm ON (((bm.board_id = d.board_id) AND (bm.user_id = auth.uid())))) WHERE (d.id = demand_dependencies.demand_id)))) WITH CHECK ((EXISTS ( SELECT 1 FROM (demands d JOIN board_members bm ON (((bm.board_id = d.board_id) AND (bm.user_id = auth.uid())))) WHERE (d.id = demand_dependencies.demand_id))));
CREATE POLICY "Anonymous can view general interactions for shared demands" ON public.demand_interactions FOR SELECT TO anon USING ((is_demand_shared(demand_id) AND (channel = 'general'::text)));
CREATE POLICY "Authenticated can view general interactions for shared demands" ON public.demand_interactions FOR SELECT TO authenticated USING ((is_demand_shared(demand_id) AND (channel = 'general'::text)));
CREATE POLICY "Team members can create interactions with channel check" ON public.demand_interactions FOR INSERT TO authenticated WITH CHECK (((auth.uid() = user_id) AND (auth.uid() IN ( SELECT tm.user_id FROM (team_members tm JOIN demands d ON ((d.team_id = tm.team_id))) WHERE (d.id = demand_interactions.demand_id))) AND can_view_demand_channel(auth.uid(), demand_id, channel)));
CREATE POLICY "Team members can view interactions with channel check" ON public.demand_interactions FOR SELECT TO authenticated USING ((can_view_demand_channel(auth.uid(), demand_id, channel) AND (auth.uid() IN ( SELECT tm.user_id FROM (team_members tm JOIN demands d ON ((d.team_id = tm.team_id))) WHERE (d.id = demand_interactions.demand_id)))));
CREATE POLICY "Users can delete own comments only" ON public.demand_interactions FOR DELETE TO public USING (((auth.uid() = user_id) AND (interaction_type = 'comment'::text)));
CREATE POLICY "Users can update own comments only" ON public.demand_interactions FOR UPDATE TO public USING (((auth.uid() = user_id) AND (interaction_type = 'comment'::text)));
CREATE POLICY "Admins can view request attachments" ON public.demand_request_attachments FOR SELECT TO public USING ((demand_request_id IN ( SELECT demand_requests.id FROM demand_requests WHERE is_team_admin_or_moderator(auth.uid(), demand_requests.team_id))));
CREATE POLICY "Board members can upload comment attachments" ON public.demand_request_attachments FOR INSERT TO public WITH CHECK (((auth.uid() = uploaded_by) AND (comment_id IS NOT NULL) AND (EXISTS ( SELECT 1 FROM (demand_request_comments c JOIN demand_requests dr ON ((dr.id = c.request_id))) WHERE ((c.id = demand_request_attachments.comment_id) AND is_team_member(auth.uid(), dr.team_id))))));
CREATE POLICY "Users can delete own request attachments" ON public.demand_request_attachments FOR DELETE TO public USING ((uploaded_by = auth.uid()));
CREATE POLICY "Users can upload attachments to own requests" ON public.demand_request_attachments FOR INSERT TO public WITH CHECK (((uploaded_by = auth.uid()) AND (demand_request_id IN ( SELECT demand_requests.id FROM demand_requests WHERE (demand_requests.created_by = auth.uid())))));
CREATE POLICY "Users can view own request attachments" ON public.demand_request_attachments FOR SELECT TO public USING ((demand_request_id IN ( SELECT demand_requests.id FROM demand_requests WHERE (demand_requests.created_by = auth.uid()))));
CREATE POLICY "Team members can create demand request comments" ON public.demand_request_comments FOR INSERT TO public WITH CHECK (((auth.uid() = user_id) AND (EXISTS ( SELECT 1 FROM demand_requests dr WHERE ((dr.id = demand_request_comments.request_id) AND is_team_member(auth.uid(), dr.team_id))))));
CREATE POLICY "Team members can view request comments" ON public.demand_request_comments FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM demand_requests dr WHERE ((dr.id = demand_request_comments.request_id) AND ((dr.created_by = auth.uid()) OR is_team_admin_or_moderator(auth.uid(), dr.team_id) OR (EXISTS ( SELECT 1 FROM (board_members bm JOIN boards b ON ((b.id = bm.board_id))) WHERE ((b.team_id = dr.team_id) AND (bm.user_id = auth.uid())))))))));
CREATE POLICY "Users can delete own request comments" ON public.demand_request_comments FOR DELETE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can update own request comments" ON public.demand_request_comments FOR UPDATE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Admins and moderators can update team requests" ON public.demand_requests FOR UPDATE TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Admins and moderators can view team requests" ON public.demand_requests FOR SELECT TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Board members can view requests for their boards" ON public.demand_requests FOR SELECT TO public USING (((board_id IS NOT NULL) AND is_board_member(auth.uid(), board_id)));
CREATE POLICY "Solicitantes can create their own requests" ON public.demand_requests FOR INSERT TO public WITH CHECK ((auth.uid() = created_by));
CREATE POLICY "Users can delete their own pending requests" ON public.demand_requests FOR DELETE TO public USING (((auth.uid() = created_by) AND (status = 'pending'::text)));
CREATE POLICY "Users can update their own pending/returned requests" ON public.demand_requests FOR UPDATE TO public USING (((auth.uid() = created_by) AND (status = ANY (ARRAY['pending'::text, 'returned'::text]))));
CREATE POLICY "Users can view their own requests" ON public.demand_requests FOR SELECT TO public USING ((auth.uid() = created_by));
CREATE POLICY "Board members can create share tokens" ON public.demand_share_tokens FOR INSERT TO authenticated WITH CHECK (((auth.uid() = created_by) AND (demand_id IN ( SELECT d.id FROM demands d WHERE (d.board_id IN ( SELECT get_user_board_ids(auth.uid())))))));
CREATE POLICY "Board members can delete share tokens" ON public.demand_share_tokens FOR DELETE TO authenticated USING ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.board_id IN ( SELECT get_user_board_ids(auth.uid()))))));
CREATE POLICY "Board members can update share tokens" ON public.demand_share_tokens FOR UPDATE TO authenticated USING ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.board_id IN ( SELECT get_user_board_ids(auth.uid())))))) WITH CHECK ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.board_id IN ( SELECT get_user_board_ids(auth.uid()))))));
CREATE POLICY "Board members can view share tokens" ON public.demand_share_tokens FOR SELECT TO authenticated USING ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.board_id IN ( SELECT get_user_board_ids(auth.uid()))))));
CREATE POLICY "Admins can manage statuses" ON public.demand_statuses FOR ALL TO public USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Anyone can view system statuses" ON public.demand_statuses FOR SELECT TO public USING ((board_id IS NULL));
CREATE POLICY "Board admins can create custom statuses for their board" ON public.demand_statuses FOR INSERT TO authenticated WITH CHECK (((board_id IS NOT NULL) AND is_board_admin_or_moderator(auth.uid(), board_id)));
CREATE POLICY "Board admins can delete custom statuses from their board" ON public.demand_statuses FOR DELETE TO authenticated USING (((is_system = false) AND (board_id IS NOT NULL) AND is_board_admin_or_moderator(auth.uid(), board_id)));
CREATE POLICY "Board admins can update custom statuses" ON public.demand_statuses FOR UPDATE TO authenticated USING (((board_id IS NOT NULL) AND is_board_admin_or_moderator(auth.uid(), board_id))) WITH CHECK (((board_id IS NOT NULL) AND is_board_admin_or_moderator(auth.uid(), board_id)));
CREATE POLICY "Board members can view custom statuses" ON public.demand_statuses FOR SELECT TO authenticated USING (((board_id IS NOT NULL) AND is_board_member(auth.uid(), board_id)));
CREATE POLICY "Team members can create subtasks" ON public.demand_subtasks FOR INSERT TO public WITH CHECK ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.team_id IN ( SELECT get_user_team_ids(auth.uid()))))));
CREATE POLICY "Team members can delete subtasks" ON public.demand_subtasks FOR DELETE TO public USING ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.team_id IN ( SELECT get_user_team_ids(auth.uid()))))));
CREATE POLICY "Team members can update subtasks" ON public.demand_subtasks FOR UPDATE TO public USING ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.team_id IN ( SELECT get_user_team_ids(auth.uid()))))));
CREATE POLICY "Team members can view subtasks" ON public.demand_subtasks FOR SELECT TO public USING ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.team_id IN ( SELECT get_user_team_ids(auth.uid()))))));
CREATE POLICY "Team admins can create templates" ON public.demand_templates FOR INSERT TO public WITH CHECK (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team admins can delete templates" ON public.demand_templates FOR DELETE TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team admins can update templates" ON public.demand_templates FOR UPDATE TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team members can view templates" ON public.demand_templates FOR SELECT TO public USING ((team_id IN ( SELECT get_user_team_ids(auth.uid()))));
CREATE POLICY "Team members can view time entries" ON public.demand_time_entries FOR SELECT TO public USING ((demand_id IN ( SELECT d.id FROM demands d WHERE (d.team_id IN ( SELECT get_user_team_ids(auth.uid()))))));
CREATE POLICY "Users can create their own time entries" ON public.demand_time_entries FOR INSERT TO public WITH CHECK (((auth.uid() = user_id) AND (demand_id IN ( SELECT d.id FROM demands d WHERE (d.team_id IN ( SELECT get_user_team_ids(auth.uid())))))));
CREATE POLICY "Users can delete their own time entries" ON public.demand_time_entries FOR DELETE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can update their own time entries" ON public.demand_time_entries FOR UPDATE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Anonymous can view shared demands" ON public.demands FOR SELECT TO authenticated, anon USING (is_demand_shared(id));
CREATE POLICY "Board members can create demands" ON public.demands FOR INSERT TO public WITH CHECK ((board_id IN ( SELECT get_user_board_ids(auth.uid()))));
CREATE POLICY "Board members can update demands" ON public.demands FOR UPDATE TO public USING ((board_id IN ( SELECT get_user_board_ids(auth.uid()))));
CREATE POLICY "Board members can view demands" ON public.demands FOR SELECT TO public USING ((board_id IN ( SELECT get_user_board_ids(auth.uid()))));
CREATE POLICY "Users can delete their own tokens" ON public.google_calendar_tokens FOR DELETE TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can insert their own tokens" ON public.google_calendar_tokens FOR INSERT TO authenticated WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can update their own tokens" ON public.google_calendar_tokens FOR UPDATE TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view their own tokens" ON public.google_calendar_tokens FOR SELECT TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Team members can create note share tokens" ON public.note_share_tokens FOR INSERT TO authenticated WITH CHECK (((auth.uid() = created_by) AND (note_id IN ( SELECT n.id FROM notes n WHERE is_team_member(auth.uid(), n.team_id)))));
CREATE POLICY "Team members can view note share tokens" ON public.note_share_tokens FOR SELECT TO authenticated USING ((note_id IN ( SELECT n.id FROM notes n WHERE is_team_member(auth.uid(), n.team_id))));
CREATE POLICY "Token creators can delete their tokens" ON public.note_share_tokens FOR DELETE TO authenticated USING ((auth.uid() = created_by));
CREATE POLICY "Token creators can update their tokens" ON public.note_share_tokens FOR UPDATE TO authenticated USING ((auth.uid() = created_by)) WITH CHECK ((auth.uid() = created_by));
CREATE POLICY "Note owner can manage shares" ON public.note_shares FOR ALL TO public USING (is_note_owner(note_id, auth.uid()));
CREATE POLICY "Users can leave shared notes" ON public.note_shares FOR DELETE TO authenticated USING ((shared_with_user_id = auth.uid()));
CREATE POLICY "Users can view shares they received" ON public.note_shares FOR SELECT TO public USING ((shared_with_user_id = auth.uid()));
CREATE POLICY "Team admins can delete tags" ON public.note_tags FOR DELETE TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team admins can update tags" ON public.note_tags FOR UPDATE TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team members can create tags" ON public.note_tags FOR INSERT TO public WITH CHECK ((is_team_member(auth.uid(), team_id) AND (auth.uid() = created_by)));
CREATE POLICY "Team members can view tags" ON public.note_tags FOR SELECT TO public USING (is_team_member(auth.uid(), team_id));
CREATE POLICY "Anonymous can view shared notes" ON public.notes FOR SELECT TO public USING (is_note_shared(id));
CREATE POLICY "Note creators can delete their notes" ON public.notes FOR DELETE TO public USING ((auth.uid() = created_by));
CREATE POLICY "Note creators can update their notes" ON public.notes FOR UPDATE TO public USING ((auth.uid() = created_by));
CREATE POLICY "Team members can create notes" ON public.notes FOR INSERT TO public WITH CHECK ((is_team_member(auth.uid(), team_id) AND (auth.uid() = created_by)));
CREATE POLICY "Team members can view notes" ON public.notes FOR SELECT TO public USING (is_team_member(auth.uid(), team_id));
CREATE POLICY "Users can update notes they own or have editor access" ON public.notes FOR UPDATE TO public USING (can_edit_note(id, auth.uid())) WITH CHECK (can_edit_note(id, auth.uid()));
CREATE POLICY "Users can view notes shared with them" ON public.notes FOR SELECT TO public USING (is_note_shared_with_user(id, auth.uid()));
CREATE POLICY "Users can insert own notifications" ON public.notifications FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Payments cannot be deleted by users" ON public.payments FOR DELETE TO public USING (false);
CREATE POLICY "Payments cannot be updated by users" ON public.payments FOR UPDATE TO public USING (false);
CREATE POLICY "Team admins can view team payments" ON public.payments FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM demand_requests dr WHERE ((dr.id = payments.demand_request_id) AND is_team_admin_or_moderator(auth.uid(), dr.team_id)))));
CREATE POLICY "Users can create their own payments" ON public.payments FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can view their own payments" ON public.payments FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Admins can insert plans" ON public.plans FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Admins can update plans" ON public.plans FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'::app_role)) WITH CHECK (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Anyone can view active plans" ON public.plans FOR SELECT TO public USING ((is_active = true));
CREATE POLICY "Admins can view all profiles" ON public.profiles FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Anonymous can view profiles for shared demands" ON public.profiles FOR SELECT TO authenticated, anon USING (((id IN ( SELECT d.created_by FROM demands d WHERE is_demand_shared(d.id) UNION SELECT da.user_id FROM (demand_assignees da JOIN demands d ON ((d.id = da.demand_id))) WHERE is_demand_shared(d.id) UNION SELECT di.user_id FROM (demand_interactions di JOIN demands d ON ((d.id = di.demand_id))) WHERE is_demand_shared(d.id))) OR (id IN ( SELECT n.created_by FROM notes n WHERE is_note_shared(n.id)))));
CREATE POLICY "Anonymous can view profiles for shared notes" ON public.profiles FOR SELECT TO anon USING ((id IN ( SELECT n.created_by FROM notes n WHERE is_note_shared(n.id))));
CREATE POLICY "Team members can view teammate profiles" ON public.profiles FOR SELECT TO authenticated USING (((auth.uid() = id) OR (id IN ( SELECT tm.user_id FROM team_members tm WHERE (tm.team_id IN ( SELECT get_user_team_ids(auth.uid()))))) OR (id IN ( SELECT bm.user_id FROM board_members bm WHERE (bm.board_id IN ( SELECT get_user_board_ids(auth.uid())))))));
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK ((auth.uid() = id));
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE TO public USING ((auth.uid() = id));
CREATE POLICY "Users can view project demands they can access" ON public.project_demands FOR SELECT TO authenticated USING (has_project_access(auth.uid(), project_id));
CREATE POLICY "Users with edit access can add demands to project" ON public.project_demands FOR INSERT TO authenticated WITH CHECK (has_project_edit_access(auth.uid(), project_id));
CREATE POLICY "Users with edit access can remove demands from project" ON public.project_demands FOR DELETE TO authenticated USING (has_project_edit_access(auth.uid(), project_id));
CREATE POLICY "Edit-shared users can create shares" ON public.project_shares FOR INSERT TO authenticated WITH CHECK (has_project_edit_access(auth.uid(), project_id));
CREATE POLICY "Edit-shared users can delete shares" ON public.project_shares FOR DELETE TO authenticated USING (has_project_edit_access(auth.uid(), project_id));
CREATE POLICY "Edit-shared users can update shares" ON public.project_shares FOR UPDATE TO authenticated USING (has_project_edit_access(auth.uid(), project_id)) WITH CHECK (has_project_edit_access(auth.uid(), project_id));
CREATE POLICY "Owners can create shares" ON public.project_shares FOR INSERT TO authenticated WITH CHECK (is_project_owner(auth.uid(), project_id));
CREATE POLICY "Owners can delete shares" ON public.project_shares FOR DELETE TO authenticated USING (is_project_owner(auth.uid(), project_id));
CREATE POLICY "Owners can update shares" ON public.project_shares FOR UPDATE TO authenticated USING (is_project_owner(auth.uid(), project_id)) WITH CHECK (is_project_owner(auth.uid(), project_id));
CREATE POLICY "Users can remove themselves from shares" ON public.project_shares FOR DELETE TO authenticated USING ((user_id = auth.uid()));
CREATE POLICY "Users can view shares of accessible projects" ON public.project_shares FOR SELECT TO authenticated USING (has_project_access(auth.uid(), project_id));
CREATE POLICY "Edit-shared users can update projects" ON public.projects FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1 FROM project_shares ps WHERE ((ps.project_id = projects.id) AND (ps.user_id = auth.uid()) AND (ps.permission = 'edit'::text))))) WITH CHECK ((EXISTS ( SELECT 1 FROM project_shares ps WHERE ((ps.project_id = projects.id) AND (ps.user_id = auth.uid()) AND (ps.permission = 'edit'::text)))));
CREATE POLICY "Owners can delete projects" ON public.projects FOR DELETE TO authenticated USING ((created_by = auth.uid()));
CREATE POLICY "Owners can update projects" ON public.projects FOR UPDATE TO authenticated USING ((created_by = auth.uid())) WITH CHECK ((created_by = auth.uid()));
CREATE POLICY "Team members can create projects" ON public.projects FOR INSERT TO authenticated WITH CHECK (((created_by = auth.uid()) AND is_team_member(auth.uid(), team_id)));
CREATE POLICY "Users can view accessible projects" ON public.projects FOR SELECT TO authenticated USING (((created_by = auth.uid()) OR (EXISTS ( SELECT 1 FROM project_shares ps WHERE ((ps.project_id = projects.id) AND (ps.user_id = auth.uid()))))));
CREATE POLICY "Board admins can delete recurring demands" ON public.recurring_demands FOR DELETE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board admins can update recurring demands" ON public.recurring_demands FOR UPDATE TO public USING (is_board_admin_or_moderator(auth.uid(), board_id));
CREATE POLICY "Board members can create recurring demands" ON public.recurring_demands FOR INSERT TO public WITH CHECK (((board_id IN ( SELECT get_user_board_ids(auth.uid()))) AND (auth.uid() = created_by)));
CREATE POLICY "Board members can view recurring demands" ON public.recurring_demands FOR SELECT TO public USING ((board_id IN ( SELECT get_user_board_ids(auth.uid()))));
CREATE POLICY "Creator can delete own recurring demands" ON public.recurring_demands FOR DELETE TO public USING ((auth.uid() = created_by));
CREATE POLICY "Creator can update own recurring demands" ON public.recurring_demands FOR UPDATE TO public USING ((auth.uid() = created_by));
CREATE POLICY "Anonymous can view services for shared demands" ON public.services FOR SELECT TO authenticated, anon USING ((id IN ( SELECT d.service_id FROM demands d WHERE is_demand_shared(d.id))));
CREATE POLICY "Team admins and moderators can create services" ON public.services FOR INSERT TO public WITH CHECK (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team admins and moderators can update services" ON public.services FOR UPDATE TO public USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team admins can delete services" ON public.services FOR DELETE TO public USING (has_team_role(auth.uid(), team_id, 'admin'::team_role));
CREATE POLICY "Team members can view services" ON public.services FOR SELECT TO public USING ((team_id IN ( SELECT get_user_team_ids(auth.uid()))));
CREATE POLICY "Admins can view all subscriptions" ON public.subscriptions FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Team admins can delete subscription" ON public.subscriptions FOR DELETE TO public USING (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team admins can insert subscription" ON public.subscriptions FOR INSERT TO public WITH CHECK (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team admins can update subscription" ON public.subscriptions FOR UPDATE TO public USING (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team members can view their subscription" ON public.subscriptions FOR SELECT TO public USING (is_team_member(auth.uid(), team_id));
CREATE POLICY "Team owners can update requests" ON public.team_join_requests FOR UPDATE TO public USING (is_team_owner(auth.uid(), team_id));
CREATE POLICY "Team owners can view team requests" ON public.team_join_requests FOR SELECT TO public USING (is_team_owner(auth.uid(), team_id));
CREATE POLICY "Users can create join requests" ON public.team_join_requests FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can delete own non-pending requests" ON public.team_join_requests FOR DELETE TO authenticated USING (((auth.uid() = user_id) AND (status = ANY (ARRAY['rejected'::text, 'approved'::text]))));
CREATE POLICY "Users can view own requests" ON public.team_join_requests FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Admins can view all team members" ON public.team_members FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Team creators can add self as owner" ON public.team_members FOR INSERT TO authenticated WITH CHECK (((auth.uid() = user_id) AND (role = 'admin'::team_role) AND is_team_creator(auth.uid(), team_id)));
CREATE POLICY "Team owners can add members" ON public.team_members FOR INSERT TO authenticated WITH CHECK ((is_team_owner(auth.uid(), team_id) AND (role = 'requester'::team_role)));
CREATE POLICY "Team owners can remove members" ON public.team_members FOR DELETE TO authenticated USING (is_team_owner(auth.uid(), team_id));
CREATE POLICY "Team owners can update members" ON public.team_members FOR UPDATE TO authenticated USING (is_team_owner(auth.uid(), team_id)) WITH CHECK (is_team_owner(auth.uid(), team_id));
CREATE POLICY "Users can leave teams" ON public.team_members FOR DELETE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can view team members of their teams" ON public.team_members FOR SELECT TO public USING ((team_id IN ( SELECT get_user_team_ids(auth.uid()))));
CREATE POLICY "Team admin and moderator can create positions" ON public.team_positions FOR INSERT TO authenticated WITH CHECK (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team admin and moderator can update positions" ON public.team_positions FOR UPDATE TO authenticated USING (is_team_admin_or_moderator(auth.uid(), team_id));
CREATE POLICY "Team admin can delete positions" ON public.team_positions FOR DELETE TO authenticated USING (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team members can view positions" ON public.team_positions FOR SELECT TO authenticated USING (is_team_member(auth.uid(), team_id));
CREATE POLICY "Admins can view all teams" ON public.teams FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Authenticated users can create teams" ON public.teams FOR INSERT TO public WITH CHECK ((auth.uid() = created_by));
CREATE POLICY "Team creators can update their teams" ON public.teams FOR UPDATE TO public USING ((auth.uid() = created_by));
CREATE POLICY "Team owners can delete teams" ON public.teams FOR DELETE TO authenticated USING (is_team_owner(auth.uid(), id));
CREATE POLICY "Users can view their teams" ON public.teams FOR SELECT TO authenticated USING (((auth.uid() = created_by) OR (auth.uid() IN ( SELECT team_members.user_id FROM team_members WHERE (team_members.team_id = teams.id)))));
CREATE POLICY "Admins can manage coupons" ON public.trial_coupons FOR ALL TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Authenticated can validate coupons" ON public.trial_coupons FOR SELECT TO authenticated USING (((is_active = true) AND ((expires_at IS NULL) OR (expires_at > now())) AND (times_used < max_uses)));
CREATE POLICY "Admins can insert usage records" ON public.usage_records FOR INSERT TO authenticated WITH CHECK (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Admins can update usage records" ON public.usage_records FOR UPDATE TO authenticated USING (is_team_admin(auth.uid(), team_id)) WITH CHECK (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team members can view their usage" ON public.usage_records FOR SELECT TO public USING (is_team_member(auth.uid(), team_id));
CREATE POLICY "Users can delete own preferences" ON public.user_preferences FOR DELETE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can insert own preferences" ON public.user_preferences FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can update own preferences" ON public.user_preferences FOR UPDATE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own preferences" ON public.user_preferences FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Users can view own roles" ON public.user_roles FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Team admins can view webhook logs" ON public.webhook_logs FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM webhook_subscriptions ws WHERE ((ws.id = webhook_logs.subscription_id) AND is_team_admin(auth.uid(), ws.team_id)))));
CREATE POLICY "Team admins can delete webhook subscriptions" ON public.webhook_subscriptions FOR DELETE TO authenticated USING (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team admins can insert webhook subscriptions" ON public.webhook_subscriptions FOR INSERT TO authenticated WITH CHECK (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team admins can select webhook subscriptions" ON public.webhook_subscriptions FOR SELECT TO authenticated USING (is_team_admin(auth.uid(), team_id));
CREATE POLICY "Team admins can update webhook subscriptions" ON public.webhook_subscriptions FOR UPDATE TO authenticated USING (is_team_admin(auth.uid(), team_id)) WITH CHECK (is_team_admin(auth.uid(), team_id));
CREATE POLICY "System admins view whatsapp logs" ON public.whatsapp_inbound_logs FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Users manage own phone codes" ON public.whatsapp_phone_codes FOR ALL TO authenticated USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));