ALTER TABLE public.api_keys ADD FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.api_keys ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.api_logs ADD FOREIGN KEY (api_key_id) REFERENCES api_keys(id) ON DELETE CASCADE;
ALTER TABLE public.board_approval_notify_settings ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.board_members ADD FOREIGN KEY (added_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.board_members ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.board_members ADD FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.board_services ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.board_services ADD FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE;
ALTER TABLE public.board_statuses ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.board_statuses ADD FOREIGN KEY (status_id) REFERENCES demand_statuses(id) ON DELETE CASCADE;
ALTER TABLE public.board_summary_history ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.board_summary_history ADD FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.board_summary_share_tokens ADD FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.board_summary_share_tokens ADD FOREIGN KEY (summary_id) REFERENCES board_summary_history(id) ON DELETE CASCADE;
ALTER TABLE public.board_whatsapp_keywords ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.board_whatsapp_keywords ADD FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.boards ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.contracts ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.contracts ADD FOREIGN KEY (uploaded_by) REFERENCES auth.users(id);
ALTER TABLE public.coupon_redemptions ADD FOREIGN KEY (coupon_id) REFERENCES trial_coupons(id);
ALTER TABLE public.coupon_redemptions ADD FOREIGN KEY (redeemed_by) REFERENCES auth.users(id);
ALTER TABLE public.coupon_redemptions ADD FOREIGN KEY (team_id) REFERENCES teams(id);
ALTER TABLE public.demand_approval_notify_settings ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demand_assignees ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demand_assignees ADD FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.demand_attachments ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demand_attachments ADD FOREIGN KEY (interaction_id) REFERENCES demand_interactions(id) ON DELETE SET NULL;
ALTER TABLE public.demand_attachments ADD FOREIGN KEY (uploaded_by) REFERENCES profiles(id);
ALTER TABLE public.demand_dependencies ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demand_dependencies ADD FOREIGN KEY (depends_on_demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demand_interactions ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demand_interactions ADD FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.demand_request_attachments ADD FOREIGN KEY (comment_id) REFERENCES demand_request_comments(id) ON DELETE CASCADE;
ALTER TABLE public.demand_request_attachments ADD FOREIGN KEY (demand_request_id) REFERENCES demand_requests(id) ON DELETE CASCADE;
ALTER TABLE public.demand_request_attachments ADD FOREIGN KEY (uploaded_by) REFERENCES profiles(id);
ALTER TABLE public.demand_request_comments ADD FOREIGN KEY (request_id) REFERENCES demand_requests(id) ON DELETE CASCADE;
ALTER TABLE public.demand_requests ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE SET NULL;
ALTER TABLE public.demand_requests ADD FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.demand_requests ADD FOREIGN KEY (responded_by) REFERENCES profiles(id);
ALTER TABLE public.demand_requests ADD FOREIGN KEY (service_id) REFERENCES services(id);
ALTER TABLE public.demand_requests ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.demand_share_tokens ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demand_statuses ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.demand_subtasks ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demand_templates ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.demand_templates ADD FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.demand_templates ADD FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL;
ALTER TABLE public.demand_templates ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.demand_time_entries ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demands ADD FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.demands ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.demands ADD FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.demands ADD FOREIGN KEY (parent_demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.demands ADD FOREIGN KEY (recurring_demand_id) REFERENCES recurring_demands(id) ON DELETE SET NULL;
ALTER TABLE public.demands ADD FOREIGN KEY (service_id) REFERENCES services(id);
ALTER TABLE public.demands ADD FOREIGN KEY (status_changed_by) REFERENCES profiles(id);
ALTER TABLE public.demands ADD FOREIGN KEY (status_id) REFERENCES demand_statuses(id);
ALTER TABLE public.demands ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.google_calendar_tokens ADD FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.note_share_tokens ADD FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.note_share_tokens ADD FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE;
ALTER TABLE public.note_shares ADD FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE;
ALTER TABLE public.note_shares ADD FOREIGN KEY (shared_by_user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.note_shares ADD FOREIGN KEY (shared_with_user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.note_tags ADD FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.note_tags ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.notes ADD FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.notes ADD FOREIGN KEY (parent_id) REFERENCES notes(id) ON DELETE SET NULL;
ALTER TABLE public.notes ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE SET NULL;
ALTER TABLE public.payments ADD FOREIGN KEY (demand_request_id) REFERENCES demand_requests(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD FOREIGN KEY (default_whatsapp_board_id) REFERENCES boards(id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.project_demands ADD FOREIGN KEY (demand_id) REFERENCES demands(id) ON DELETE CASCADE;
ALTER TABLE public.project_demands ADD FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.project_shares ADD FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.project_shares ADD FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.projects ADD FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.projects ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.recurring_demands ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE public.recurring_demands ADD FOREIGN KEY (service_id) REFERENCES services(id);
ALTER TABLE public.recurring_demands ADD FOREIGN KEY (status_id) REFERENCES demand_statuses(id);
ALTER TABLE public.recurring_demands ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.services ADD FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE SET NULL;
ALTER TABLE public.services ADD FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.services ADD FOREIGN KEY (parent_id) REFERENCES services(id) ON DELETE SET NULL;
ALTER TABLE public.services ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.subscriptions ADD FOREIGN KEY (plan_id) REFERENCES plans(id);
ALTER TABLE public.subscriptions ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.team_join_requests ADD FOREIGN KEY (responded_by) REFERENCES profiles(id);
ALTER TABLE public.team_join_requests ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.team_join_requests ADD FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.team_members ADD FOREIGN KEY (position_id) REFERENCES team_positions(id) ON DELETE SET NULL;
ALTER TABLE public.team_members ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.team_members ADD FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.team_positions ADD FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.team_positions ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.teams ADD FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.trial_coupons ADD FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.trial_coupons ADD FOREIGN KEY (plan_id) REFERENCES plans(id);
ALTER TABLE public.usage_records ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.user_preferences ADD FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.webhook_logs ADD FOREIGN KEY (subscription_id) REFERENCES webhook_subscriptions(id) ON DELETE CASCADE;
ALTER TABLE public.webhook_subscriptions ADD FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.webhook_subscriptions ADD FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_inbound_logs ADD FOREIGN KEY (created_demand_id) REFERENCES demands(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_inbound_logs ADD FOREIGN KEY (created_request_id) REFERENCES demand_requests(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_inbound_logs ADD FOREIGN KEY (matched_board_id) REFERENCES boards(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_inbound_logs ADD FOREIGN KEY (matched_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_phone_codes ADD FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.api_keys TO authenticated; GRANT ALL ON public.api_keys TO service_role; GRANT SELECT ON public.api_keys TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.api_logs TO authenticated; GRANT ALL ON public.api_logs TO service_role; GRANT SELECT ON public.api_logs TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_approval_notify_settings TO authenticated; GRANT ALL ON public.board_approval_notify_settings TO service_role; GRANT SELECT ON public.board_approval_notify_settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_members TO authenticated; GRANT ALL ON public.board_members TO service_role; GRANT SELECT ON public.board_members TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_services TO authenticated; GRANT ALL ON public.board_services TO service_role; GRANT SELECT ON public.board_services TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_statuses TO authenticated; GRANT ALL ON public.board_statuses TO service_role; GRANT SELECT ON public.board_statuses TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_summary_history TO authenticated; GRANT ALL ON public.board_summary_history TO service_role; GRANT SELECT ON public.board_summary_history TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_summary_share_tokens TO authenticated; GRANT ALL ON public.board_summary_share_tokens TO service_role; GRANT SELECT ON public.board_summary_share_tokens TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_whatsapp_keywords TO authenticated; GRANT ALL ON public.board_whatsapp_keywords TO service_role; GRANT SELECT ON public.board_whatsapp_keywords TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.boards TO authenticated; GRANT ALL ON public.boards TO service_role; GRANT SELECT ON public.boards TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.contracts TO authenticated; GRANT ALL ON public.contracts TO service_role; GRANT SELECT ON public.contracts TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.coupon_redemptions TO authenticated; GRANT ALL ON public.coupon_redemptions TO service_role; GRANT SELECT ON public.coupon_redemptions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_approval_notify_settings TO authenticated; GRANT ALL ON public.demand_approval_notify_settings TO service_role; GRANT SELECT ON public.demand_approval_notify_settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_assignees TO authenticated; GRANT ALL ON public.demand_assignees TO service_role; GRANT SELECT ON public.demand_assignees TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_attachments TO authenticated; GRANT ALL ON public.demand_attachments TO service_role; GRANT SELECT ON public.demand_attachments TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_dependencies TO authenticated; GRANT ALL ON public.demand_dependencies TO service_role; GRANT SELECT ON public.demand_dependencies TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_interactions TO authenticated; GRANT ALL ON public.demand_interactions TO service_role; GRANT SELECT ON public.demand_interactions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_request_attachments TO authenticated; GRANT ALL ON public.demand_request_attachments TO service_role; GRANT SELECT ON public.demand_request_attachments TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_request_comments TO authenticated; GRANT ALL ON public.demand_request_comments TO service_role; GRANT SELECT ON public.demand_request_comments TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_requests TO authenticated; GRANT ALL ON public.demand_requests TO service_role; GRANT SELECT ON public.demand_requests TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_share_tokens TO authenticated; GRANT ALL ON public.demand_share_tokens TO service_role; GRANT SELECT ON public.demand_share_tokens TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_statuses TO authenticated; GRANT ALL ON public.demand_statuses TO service_role; GRANT SELECT ON public.demand_statuses TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_subtasks TO authenticated; GRANT ALL ON public.demand_subtasks TO service_role; GRANT SELECT ON public.demand_subtasks TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_templates TO authenticated; GRANT ALL ON public.demand_templates TO service_role; GRANT SELECT ON public.demand_templates TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demand_time_entries TO authenticated; GRANT ALL ON public.demand_time_entries TO service_role; GRANT SELECT ON public.demand_time_entries TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demands TO authenticated; GRANT ALL ON public.demands TO service_role; GRANT SELECT ON public.demands TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.google_calendar_tokens TO authenticated; GRANT ALL ON public.google_calendar_tokens TO service_role; GRANT SELECT ON public.google_calendar_tokens TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.note_share_tokens TO authenticated; GRANT ALL ON public.note_share_tokens TO service_role; GRANT SELECT ON public.note_share_tokens TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.note_shares TO authenticated; GRANT ALL ON public.note_shares TO service_role; GRANT SELECT ON public.note_shares TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.note_tags TO authenticated; GRANT ALL ON public.note_tags TO service_role; GRANT SELECT ON public.note_tags TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notes TO authenticated; GRANT ALL ON public.notes TO service_role; GRANT SELECT ON public.notes TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notifications TO authenticated; GRANT ALL ON public.notifications TO service_role; GRANT SELECT ON public.notifications TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payments TO authenticated; GRANT ALL ON public.payments TO service_role; GRANT SELECT ON public.payments TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.plans TO authenticated; GRANT ALL ON public.plans TO service_role; GRANT SELECT ON public.plans TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role; GRANT SELECT ON public.profiles TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.project_demands TO authenticated; GRANT ALL ON public.project_demands TO service_role; GRANT SELECT ON public.project_demands TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.project_shares TO authenticated; GRANT ALL ON public.project_shares TO service_role; GRANT SELECT ON public.project_shares TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO authenticated; GRANT ALL ON public.projects TO service_role; GRANT SELECT ON public.projects TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.recurring_demands TO authenticated; GRANT ALL ON public.recurring_demands TO service_role; GRANT SELECT ON public.recurring_demands TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.services TO authenticated; GRANT ALL ON public.services TO service_role; GRANT SELECT ON public.services TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.subscriptions TO authenticated; GRANT ALL ON public.subscriptions TO service_role; GRANT SELECT ON public.subscriptions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_join_requests TO authenticated; GRANT ALL ON public.team_join_requests TO service_role; GRANT SELECT ON public.team_join_requests TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_members TO authenticated; GRANT ALL ON public.team_members TO service_role; GRANT SELECT ON public.team_members TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_positions TO authenticated; GRANT ALL ON public.team_positions TO service_role; GRANT SELECT ON public.team_positions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.teams TO authenticated; GRANT ALL ON public.teams TO service_role; GRANT SELECT ON public.teams TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trial_coupons TO authenticated; GRANT ALL ON public.trial_coupons TO service_role; GRANT SELECT ON public.trial_coupons TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.usage_records TO authenticated; GRANT ALL ON public.usage_records TO service_role; GRANT SELECT ON public.usage_records TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_preferences TO authenticated; GRANT ALL ON public.user_preferences TO service_role; GRANT SELECT ON public.user_preferences TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role; GRANT SELECT ON public.user_roles TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.webhook_logs TO authenticated; GRANT ALL ON public.webhook_logs TO service_role; GRANT SELECT ON public.webhook_logs TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.webhook_subscriptions TO authenticated; GRANT ALL ON public.webhook_subscriptions TO service_role; GRANT SELECT ON public.webhook_subscriptions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.whatsapp_inbound_logs TO authenticated; GRANT ALL ON public.whatsapp_inbound_logs TO service_role; GRANT SELECT ON public.whatsapp_inbound_logs TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.whatsapp_phone_codes TO authenticated; GRANT ALL ON public.whatsapp_phone_codes TO service_role; GRANT SELECT ON public.whatsapp_phone_codes TO anon;